### ISSUE TITLE
no return url given end wrong sso endpoint

### ISSUE THREAD

**Issue by verymilan** [pcd1193182/dokuwiki-discourse-sso#1]
Hello, first of all, thank you very much for this fork!

Second, it appears that there is no `return_sso_url` given by default, the link does lead to the configured baseurl of discourse with only the request flags while discourse by default listens at `/session/sso_provider`.

I adjusted the configfile so it runs against `/session/sso_provider` and adjusted `inc/html.php` so it looks like this: `print '<a href="' . $cfg_sso_url . '?sso=' . $payload . '&sig=' . $sig . '&return_sso_url=' . $cfg_url_base .'">Log In with SSO</a>';`

However now my discourse is complaining: *"return_sso_url is blank, it must be provided"*
Well it is provided, i have no idea what to do right now. :(

**Comment by pcd1193182** [comment]
It looks to me like that parameter is used when you are using discourse as an SSO provider. This is the opposite use case that this tool is intended to solve; this addon allows you to have auth for dokuwiki provided by an existing sso service, using the flow as described in https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045 .  Does that answer your question? I'll mark this closed, and if I hear back that I've misunderstood I'm happy to reopen and investigate further.
